services:
  app:
    container_name: arr-app
    image: addyi/arr:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080" # HOST_PORT:CONTAINER_PORT
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: arr-postgres
    image: postgres:13
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${DB_HOST} -p 5432 -U ${PG_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: { }
