name: on-push-main

on:
  push:
    branches:
      - main
  # Manual trigger
  workflow_dispatch:

# Cancels in-progress workflows if a new one is triggered
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Only write to the cache for builds on 'main' branch. Other branches are read only.
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Run ktlint check
      run: ./gradlew ktlintCheck
      timeout-minutes: 5

    - name: Run detekt
      run: ./gradlew detekt
      timeout-minutes: 5

    - name: Append detekt reports to step summary
      run: |
        cat build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY
        printf "\n---\n\n" >> $GITHUB_STEP_SUMMARY
